---
- hosts: nodo2
  become: yes
  tasks:
    - name: Install nginx
      apt: name=nginx state=latest update_cache=yes

    - name: Configuracion nginx
      template: 
           src=default.conf 
           dest=/etc/nginx/sites-available/default

    - name: restart nginx
      service: name=nginx state=restarted
