---
- hosts: nodo1
  become: yes
  tasks:
    - name: Install mysql
      apt: name={{ item }} state=present
      with_items:
       - mysql-server
       - python-mysqldb

    - name: Configuracion mysql
      template: 
           src=50-server.cnf 
           dest=/etc/mysql/mariadb.conf.d/50-server.cnf

    - name: Creando base de datos
      mysql_db: name=bascon state=present

    - name: Creando usuario
      mysql_user: name=bascon password=bascon priv=bascon.*:ALL host=% state=present
  
    - name: Copiando BBDD Wordpress
      template: src=bascon.sql dest=/home/vagrant

    - name: Migrando BBDD Wordpress
      mysql_db: name=bascon state=import target=/home/vagrant/bascon.sql

    - name: restart mysql
      service: name=mysql state=restarted      
