---
- hosts: nodo1
  become: yes
  tasks:
    - name: Install mysql
      apt: name=mariadb-server state=latest update_cache=yes

    - name: Configuracion mysql
      template: 
           src=my.cnf 
           dest=/etc/mysql/mariadb.conf.d/50-server.cnf

    - name: restart mysql
      service: name=mysql state=restarted

