---
- hosts: nodo1
  become: yes
  tasks:
     - name: Install bind9
       action: apt name={{ item }} state=installed update_cache=yes
       with_items:
         - bind9
         - dnsutils

     - name: Configurando bind9
       copy: src=named.conf.local dest=/etc/bind/named.conf.local

     - name: Copiando zona directa
       template: src=db.iesgn.org dest=/var/cache/bind/db.iesgn.org

     - name: Reiniciando bind9
       service: name=bind9 state=restarted
